### ISSUE TITLE
simpler tvm_eq()

### ISSUE THREAD

**Issue by achan001** [thomasokken/plus42desktop#1]
From core_commands9.cc
```
static phloat tvm_eq(phloat i) {
    phloat pmt = tvm_pmt;
    if (tvm_m)
        pmt *= 1 + i;
    if (i == 0)
        return pmt + (tvm_pv + tvm_fv) / tvm_n;
    else
        return pmt + ((tvm_pv + tvm_fv) / expm1(tvm_n * log1p(i)) + tvm_pv) * i;
}
```

Let **phloat tvm_m = tvm_pv + (mode==1) * tvm_pmt**, above is simplified.
(I have not studied mode ranges, if it is just 0 or 1, remove ==1 part)

It is calculated outside rate search loop, thus also more efficient.
It is based from identity:

loan_rate(n, pv, pmt, fv, mode=1) = loan_rate(n, pv+pmt, pmt, fv-pmt, mode=0)

Revised tvm_eq():
```
static phloat tvm_eq(phloat i) {
    if (i == 0)
        return tvm_pmt + (tvm_pv + tvm_fv) / tvm_n;
    else
        return tvm_pmt + ((tvm_pv + tvm_fv) / expm1(tvm_n * log1p(i)) + tv_m) * i;
}
```

**Comment by thomasokken** [comment]
I made the change: d084bc31fb2f46f12206edcb45e45ebcf94561b5

Thanks!
