### ISSUE TITLE
TVM rate guess

### ISSUE THREAD

**Issue by achan001** [thomasokken/plus42desktop#2]
This is from core_commands9.cc do_i_pct_yr()

>    phloat i = 0.0001; // Arbitrary starting guess...

I think I have a robust guess for this.

First, what's wrong with above ?
NPMT=0 with unique rate solution, nothing's wrong.
Any reasonable guess (even crazy ones) will lead to the root.

Problem is when NPMT=0 had 2 rate roots.
NPMT curve look like a concave-up V.

Hard-coded rate might be located where slope of NPMT is small.
Newton's method may over-shoot it to no man's land.
If it overshoot to the right, possbily no harm is done.

**If rate overshoot below −100%, code will break.
But, if we use rate guess from the edges, we are safe.**

"Outside" guess for concaved-up curve, Newton's method never overshoot.

```
lua> n, pv, pmt, fv = 10, 50, -30, 80
lua> g = loan_rate(n,pv,pmt,fv, 0.0001) -- hard-coded guess
lua> g(), g()
-2.0050595733488947     -NaN    -NaN

lua> pmt/fv, pmt/-pv    -- rate edges
-0.375  0.6

lua> g = loan_rate(n,pv,pmt,fv, pmt/fv) -- low rate edge
lua> g(), g(), g()
-0.3689508127377895     -0.36893369888346206    -0.3689336987417774
lua> g = loan_rate(n,pv,pmt,fv, -pmt/pv) -- high rate edge
lua> g(), g(), g()
0.5846625273989696      0.5846195530179824      0.5846195526622099
```
For how rate edges are derived:
https://www.hpmuseum.org/forum/thread-18359-post-160156.html#pid160156

**Comment by achan001** [comment]
With TMV returning 1 rate, even with 2 solutions, picking edge is subjective.
This version preferred positive edge.

```
function edge_rate(n,pv,pmt,fv)
    local a, b = pmt/fv, -pmt/pv
    if a > b then a,b = b,a end
    return a >= 0 and a or b
end

lua> edge_rate(10, 50, -30, 80) -- OP example
0.6
```

If pmt=0, edge_rate() always return 0.0 (which is OK, for starting guess)
Of course, with pmt=0, we can solve for it

pv * (1+x)^n + fv = 0
n * log1p(x) = log(-fv/pv)
x = expm1(log(-fv/pv)/n)

**Comment by achan001** [comment]
Here is a version to pick the "smaller" edge.

```
function edge_rate(n,pv,pmt,fv)
    local a, b = pmt/fv, -pmt/pv
    return (abs(b) > abs(a) and a > -1) and a or b
end

lua> edge_rate(10, 50, -30, 80) -- OP example
-0.375
```

**Comment by thomasokken** [comment]
I was curious which root the HP-17B would pick for your example, but it just replies MANY OR NO SOLUTIONS.

That is one way to deal with this problem! Another would be to use the current value of i as the starting value.

But how can you be sure in advance whether or not there is exactly one root? Is there a simple test?

**Comment by achan001** [comment]
> But how can you be sure in advance whether or not there is exactly one root? Is there a simple test?

**Descartes rules of signs**

Let **x = 1+i ≥ 0**, with positive integer n, net future value is simply a polynomial

pv * x^n + pmt * x^(n-1) + pmt * x^(n-2) + ... + pmt * x + (pmt + fv) = 0

If pv and (pmt+fv) have opposite signs, above have exactly 1 positive real root.
Otherwise, 0 or 2 solutions. (definitely no solution if all coefs have same signs)

**Comment by thomasokken** [comment]
I implemented the logic to pick the "smaller" edge as the starting guess:

82fdc993362dab8dff30be9f6adc670243d625e8

Let me know if you would like me to build a test version. I did verify the result from the original post.

**Comment by achan001** [comment]
Does code "break" if guess rate is non-finite ?
Perhaps it is safer to check for Inf/NaN **after** picked the "small" edge.

a, b = pmt/fv, -pmt/pv
if (abs(b) > abs(a) and a > -1): b = a      # b = "small" edge

if (b-b != 0): return ERR_INVALID_DATA
i = b

---

Safer way is not quit, even if both edges are bad (for rate first guess)
In other words, always supply a valid guess rate.

i = b if (b-b==0 and b>-1) else 0.0

**Comment by achan001** [comment]
Both approaches (previous post) work.

> Let x = 1+i ≥ 0, with positive integer n, net future value is simply a polynomial
> pv * x^n + pmt * x^(n-1) + pmt * x^(n-2) + ... + pmt * x + (pmt + fv) = 0

Let a = pmt/fv, b = -pmt/pv
If pmt=0, nonzero (pv, fv), we have a = b = 0%

If pmt≠0, we can factor it out, getting coefs: **[-1/b, 1, 1, ..., 1, 1+1/a]**
To have positive root, (-1/b), (1+1/a) cannot be both non-negative.

```
a   b   (-1/b)  (1+1/a)

±∞  ±∞  0       1
-1  -1  1       0
-1  -2  1/2     0
-2  -1  1       1/2
```

**Both bad edges guaranteed polynomial have no positive root.**

Note that rate edges have time symmetry.
(n,pv,pmt,fv) → (-n,fv,-pmt,pv), edges (a,b) only get swapped.
Thus, above analysis work for n < 0 too.

**Comment by thomasokken** [comment]
I already had checks for pv == 0 and fv == 0, so would this additional check be sufficient?

23416bc275525493829f6152d4af6bf3849f0df7

**Comment by achan001** [comment]
> if (p_isinf(i) || p_isnan(i) || i <= -1) i = 0;

Technically, we don't need above additional test.
It is just _cosmetically_ nicer to start with a valid guess.

If only 1 edge is bad, small edge will always be the good one.
If both edges are bad, we have no solution, and may skip searching for it.

In other words, your first version [82fdc99] is good enough.

**Comment by thomasokken** [comment]
OK, thanks!

**Comment by thomasokken** [comment]
To handle solver failures better, I could make it retry the solver, this time with the existing value of the I%YR variable as the starting value, rather than the algorithmically derived starting value. That way, in cases where the algorithm doesn't find the root on its own, the user would be able to help. I think I read somewhere that at least some HP calculators also look at the existing I%YR as a starting value, at least in certain cases.

The one question I'm not sure how to deal with is what to do when the iteration never finds a zero. How to decide whether it is stuck at a minimum, vs. having found an actual root but tvm_eq() never evaluating to zero exactly? It should accept the latest guess if the last value returned by tvm_eq() is small enough, but how small is small enough?

**Comment by achan001** [comment]
I am curious ... why not use your built-in solver ?

It accepts user supplied guesses.
Also, it handled no solution case, even provided Extremum info.
Example, for a no solution case:
```
TVM:0=(1/EXPM1(N*LNP1(I))*(PV+0*PMT+FV)+PV+BEGIN*PMT)*I+PMT
```
N=36, PV=-10000, PMT=500, FV=-9000, BEGIN=0
guess_i (small edge) = PMT/-PV = 0.05, solve for I, we have:

-6.68528759196799370894255223885718e-3 Extremum

With other edge rate guess, it also give no solution, as expected.

RCL PMT RCL FV ÷ [I] ENTER [I] [I]

-6.685287591967993722103036720471805e-3 Extremum

**Comment by thomasokken** [comment]
Yes... given that tvm_eq() is a continuous function, a sign reversal always implies the presence of a root. I could make the I%YR solver switch from Newton iteration to secant interpolation, or even bisection, once it has found two guesses that evaluate to opposite signs, and report "no root" if that never happens.

**Comment by achan001** [comment]
Redo previous 2 examples, with **Newton's method**
Convergence slower than Halley's, but 1-sided convergence remain.

```
lua> i0 = 0.05 -- small edge
lua> g = loan_rate1(36,-10000,500,-9000,i0)
lua> g()
0.015516527042798045    -0.03448347295720196
lua> g()
-0.005807052735433971   -0.021323579778232016
lua> g()
-0.25728394143346006    -0.2514768886980261
lua> g()
-0.055434067748623084   0.20184987368483698

lua> g = loan_rate1(36,-10000,500,-6000,i0)
lua> g()
0.023996885052315904    -0.0260031149476841
lua> g()
0.018412873556468905    -0.005584011495846998
lua> g()
0.018067595762622863    -0.0003452777938460427
lua> g()
0.01806623135824759     -1.364404375273669e-006
lua> g()
0.018066231336911785    -2.133580633528394e-011
lua> g()
0.01806623133691177     -1.4542308677697424e-017
lua> g()
0.018066231336911785    1.454230867769741e-017
```

**Comment by thomasokken** [comment]
86ab77ea792868be49f1c45cfd9ed3b903948bbd

After 30 consecutive steps with no improvement in the absolute value of f, stop the iteration.
If both positive and negative values of f have been seen since the last time f improved, consider the best value found until then to be an approximate root; other wise, report No Solution Found.

**Comment by achan001** [comment]
```
            phloat a = fabs(f);
            if (a < best) {
                best = a;
                impatience = 0;
                pos = neg = false;  // BUG! line should be deleted
            } else {
                impatience++;
            }
```

if f=0, or flipped sign during rate iterations, we guaranteed a solution.

If |f| < best, sign info are lost, pos = neg = false.
Now, if new_i == i, code would mistakenly assumed no solution.

---

Why 30 consecutive steps (for variable impatience) ?

I am more "impatient" :grin:
Starting from edge, I would quit if Newton's step not improving !

Actually, if f=0, or sign flip detected, it is time to terminate.
With 1-sided convergence, we do not expect sign-flip, unless at the end

We might not even need new_i == i test.

---

Another bug, with if clause not doing anything. i=0 still give h=0
It may be better to use a fixed h, say h = 1E-6

```
            phloat h = i / 10000;
            if (i + h == i)
                h = i;               // ???
```

**Comment by achan001** [comment]
> Starting from edge, I would quit if Newton's step not improving !

f not improving (toward 0) corresponded to sign-flip of eps
Below, I patched loan_rate1(n,pv,pmt,fv), returning next-rate, eps, f

```
lua> g = loan_rate1(36,-10000,500,-9000)
lua> g()
0.015516527042798045    -0.03448347295720196    -198.2546852890306
lua> g()
-0.005807052735433971   -0.021323579778232016   -53.16902917698485
lua> g()
-0.25728394143346006    -0.2514768886980261     -25.26668518452891
lua> g()
-0.055434067748623084   0.20184987368483698     -1815.6648174915672
```

**Comment by achan001** [comment]
```
if (!pos || !neg)
    return ERR_NO_SOLUTION_FOUND;
```

It may be more readable to test !(pos && neg)

> if rate is not **bracketed**, no solution found.

**Comment by thomasokken** [comment]
Agreed on the i = 0 case still being handled incorrectly, and on rephrasing the test at the end:

ae85ea098569174bce0c4589f4a0d8b8a6e50633

---

> if f=0, or flipped sign during rate iterations, we guaranteed a solution.
> 
> If |f| < best, sign info are lost, pos = neg = false. Now, if new_i == i, code would mistakenly assumed no solution.

Are we sure we'll never find ourselves straddling the pole at i = -2 ?

> Why 30 consecutive steps (for variable impatience) ?
> 
> I am more "impatient" 😁 Starting from edge, I would quit if Newton's step not improving !
> 
> Actually, if f=0, or sign flip detected, it is time to terminate. With 1-sided convergence, we do not expect sign-flip, unless at the end
> 
> We might not even need new_i == i test.

30 is a very conservative limit, I picked it for the general-purpose solver because I wanted to be sure that the solver didn't give up prematurely on functions that bounce around a lot away from the root. The limit could probably be lower here, but I wouldn't want to lower it all the way to 1, I'll sleep better with it being higher...

**Comment by achan001** [comment]
Is it simpler just use fixed h = 1e-6 ?
Slope ≈ (f(x+h)-f(x)) / h
With too small h, f(x+h)-f(x) will suffer catastrophic cancellation.
see https://en.wikipedia.org/wiki/Numerical_differentiation#Step_size

If we really want accurate slope, we should use derivative.
Bonus: this should be faster than getting both f(x) and f(x+h)
```
def f_fp(n,x,pv,pmt,fv,BEGIN=0):
    m = pv + BEGIN*pmt
    a = (fv+pv)/n
    if x==0:
        f = a + pmt
        fp = a*(1-n)/2 + m
    else:
        g = n*x/expm1(n*log1p(x))
        f = a*g + m*x + pmt
        fp = a*g*(1-g+(1-n)*x)/(x+x*x) + m
    return f, fp
```

**Comment by achan001** [comment]
> Are we sure we'll never find ourselves straddling the pole at i = -2 ?

I am not sure what this mean ...

But, on the question of convergence stability, f is very simple shape.
f is either close to straight line (1 root), or V, or inverted V (0 or 2 roots).

If we start guess from the edge, we expected all iterations to be better,
except probably the last iteration, due to tiny rounding errors.

This is very different than arbitrarily picked a rate guess.
With a guess close to f'=0, Newton's method will shoot to no-mans land.
Halley's method also have problem, since f' is on the numerator:

x = x - f * **f'** / ((f')^2 - (f''/2)*f)

x with f'≈0 hit an unstable equilibrium, which may take many tries to get out.

**Comment by thomasokken** [comment]
![Screen Shot 2022-06-10 at 11 34 38](https://user-images.githubusercontent.com/17934252/173037425-8967f845-5824-4b1f-b16f-d08e8908d50b.png)
![Screen Shot 2022-06-10 at 11 35 33](https://user-images.githubusercontent.com/17934252/173037433-f6d2bbd1-becd-49c2-8bff-e6a09ab15e58.png)

**Comment by thomasokken** [comment]
> Is it simpler just use fixed h = 1e-6 ?

Using h = i / 1e4 has the advantage of being independent of the magnitude of i. Unless you get close to the smallest representable numbers, but I'm not too worried about that scenario.

> If we really want accurate slope, we should use derivative. Bonus: this should be faster than getting both f(x) and f(x+h)

Hmm, yes, I like that idea...

**Comment by achan001** [comment]
I forget about the assumption of edge rates.
It assumed END mode.

To handle BEGIN mode, we need turn it back to END mode:

> if BEGIN: pv, fv = pv+pmt, fv-pmt

Example, n, pv, pmt, fv = 10, 50, -30, 100

END mode: edges = [pmt/fv, pmt/-pv] = [-0.3, 0.6]
BEGIN mode: edges = [pmt/(fv-pmt), pmt/-(pv+pmt)] ≈ [-0.23, 1.5]

Sorry for the mistake ...

**Comment by achan001** [comment]
> Are we sure we'll never find ourselves straddling the pole at i = -2 ?

Thanks for the plots, but tvm[i] domain is **(-1, inf)**
We only have the inverted V shape. (0 or 2 solutions)

Mathematica can plot for x ≤ -1 only because it turned:
expm1(n*log1p(x)) --> (1+x)^n - 1

BTW, edge rates equivalent to apply Newton's method to 2 extremes.
```
XCAS> tvm := ((pv+fv)/((1+x)^n-1) + pv)*x + pmt
XCAS> f := tvm(n=36, pv=-10000, pmt=500, fv=-9000)
XCAS> limit(x-f/f', x=-1), limit(x-f/f', x=inf)

(-1/18, 1/20)

XCAS> [pmt/fv, -pmt/pv] (pv=-10000, pmt=500, fv=-9000)

(-1/18, 1/20)
```

**Comment by thomasokken** [comment]
So when the iteration goes to a point < -1, should it substitute -1? That's my concern, when the iteration ends up near the extremum, it could go anywhere, even outside of the range (-1, inf)...

**Comment by achan001** [comment]
> f is either concave-up, or concave-down.

I just proved this, for n>1

https://www.hpmuseum.org/forum/thread-18359-post-161156.html#pid161156

**Comment by achan001** [comment]
**Newton's method 1-sided convergence is proven**.  I used it here.

```
function edge_i(n,pv,pmt,fv)
   local a, b = pmt/fv, -pmt/pv
   if abs(a) > abs(b) and b > -1 then a,b = b,a end
   return a, b  -- a = small edge
end

function iter_i(n, pv, pmt, fv, i)
    pmt, fv = pmt or -1, fv or 0
    i = i or edge_i(n, pv, pmt, fv)
    return function()
        if i==0 then
            local a, b = (pv+fv)/n, pv-fv
            local f, fp = (a+pmt), (a+b)*0.5
            i = -f/fp
            return i, i, f
        end
        local x = i/expm1(n*log1p(i))
        local k, y = (pv+fv)*x, n*x-1
        local f = k + pv*i + pmt
        local num, den = y+(n-1)*i, i+i*i
        x = f*den / (k*num-pv*den)
        i = i + x   -- Newton's method
        return i, x, f
    end
end

function loan_rate(n,pv,pmt,fv,i,BEGIN)
    if BEGIN then pv, fv = pv+pmt, fv-pmt end
    local g = iter_i(n,pv,pmt,fv,i)
    local i,eps,f = g()
    repeat
        local f0 = f
        i,eps,f = g()
        if f*f0 <= 0 then return i,eps end
    until abs(f0) < abs(f)
    return nil
end
```

All examples shown in this issue.

```
lua> loan_rate(10,50,-30,80)
-0.3689336987417774     0
lua> loan_rate(10,50,-30,100)
-0.284435998880256      -4.284106772739964e-017
lua> loan_rate(10,50,-30,100,nil,true) -- BEGIN mode
-0.20399537076838428    0

lua> loan_rate(36,-10000,500,-9000,500/10000)
nil
lua> loan_rate(36,-10000,500,-9000,500/-9000)
nil
lua> loan_rate(36,-10000,500,-6000)
0.018066231336911785    1.454230867769741e-017
```

**Comment by achan001** [comment]
I discovered an error of find_rate()
It is possible i fully converged, without causing f=0 (or changed sign).

Patch to fix **find_rate()**
```
< if f*f0 <= 0 then return i,eps end

> if f*f0 <= 0 or i==i-eps then return i,eps end
```

For full explanation, see [my latest post](https://www.hpmuseum.org/forum/thread-18359-post-161284.html#pid161284)

**Comment by achan001** [comment]
I translated Lua code to Python, you can get it [here](https://www.hpmuseum.org/forum/thread-18359-post-161331.html#pid161331)

BTW, your code is still not quite right.
The criteria for finding a solution is too precise.

Because of rounding errors, many cases may not detect f sign flip.

This is especially true for our f = NPMT/n
Solve for f=0 for x, Newton's method from edge, convergence is 1-sided.

Some kind of fuzz factor is required. 
Python code use (i == i - eps*0.01) criteria, if f sign flip not detected.

**Comment by achan001** [comment]
**Plus42 may hang**, if 2 roots get close.

N=30
PV=6500
FV=50000
PMT = -993.47750369345731

The reason is a bad slope, (f(x+h) - f(x)) / h, giving wrong sign.
Iterations get closer and closer to the root, then overshoot back

This generated an infinite loop.

I recommended Python code, with guaranteed termination.
If sequence of f's does not get closer to 0, even once, terminate.

**Comment by thomasokken** [comment]
I implemented your latest Lua code: https://github.com/thomasokken/plus42desktop/commit/dbf4f0460143aba1c9e6b14ba84f895d6f8aaabd

I tried several of your examples and it gives results that match the ones you gave.

**Comment by thomasokken** [comment]
Actually, the diff is a bit hard to read, because so much has changed.
Here is a link to the revised function:

https://github.com/thomasokken/plus42desktop/blob/dbf4f0460143aba1c9e6b14ba84f895d6f8aaabd/common/core_commands9.cc#L1134-L1214

**Comment by achan001** [comment]
Latest code looks good !

**Comment by thomasokken** [comment]
Great, thank you!
I'll create a new release tomorrow.
