### ISSUE TITLE
New "A...F" FCN isn't appearing in catalog, assign lists, etc.  How to access?

### ISSUE THREAD

**Issue by gwiede** [thomasokken/plus42desktop#6]
I cannot find any indication of 1.0.11's new "A...F" function anywhere in the Plus42 UI/UX.  I can't find it in CATALOG, nor ASSIGN-able, and am not sure where i should be looking (or if it somehow isn't available).  Please advise?

Thanks as always for all the hard work on Free42 and Plus42, it is very greatly appreciated!!

-John W

**Comment by thomasokken** [comment]
It's in CATALOG->MISC, but will move to CATALOG->BASE in the next release.
When spelling out the function name for XEQ or ASSIGN, be sure to write it with three periods, not an ellipsis character.

**Comment by gwiede** [comment]
Ah, yeah, okay, I wouldn't have thought to look in MISC, thus inability to find.  Good to know for now, but definitely belongs in BASE more (IMO as well).  Also, noted w.r.t. 3x '.' not 1x '…', don't think I did that, but not totally implausible.  Thanks!
