### ISSUE TITLE
power evaluated in wrong order

### ISSUE THREAD

**Issue by achan001** [thomasokken/plus42desktop#7]
**Hp50g**: '2^3^4' EVAL, it produced 2^(3^4) ≈ 2.41785E24

**Plus42**: XSTR "2^3^4" PARSE EVAL, it produced (2^3)^4 = 4096

Is this worth fixing?

**Comment by thomasokken** [comment]
I agree that this goes against the standard convention of exponentiation being right-associative, but I modeled this behavior after the HP-17B/19B/27S calculators, for the sake of compatibility. I think it would be better to keep it the way it is.
